[package]
name = "chunker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "chunker"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rayon = "1.8.1"
tiktoken-rs = "0.5.8"
